# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Back2base < Formula
  desc "Containerized Claude Code with curated MCP servers"
  homepage "https://back2base.net"
  version "0.35.0"
  license "MIT"

  depends_on "docker" => :optional

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/back2base/back2base-dist/releases/download/v0.35.0/back2base_darwin_amd64.tar.gz"
      sha256 "b26311440fb6657ace6d98a45712c430a7404a414a32bd40088834738b77397d"

      define_method(:install) do
        bin.install "back2base"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/back2base/back2base-dist/releases/download/v0.35.0/back2base_darwin_arm64.tar.gz"
      sha256 "1c91367583111b5da5e0181e10788a413483aedfe3d25cf948940fae4d51fa9a"

      define_method(:install) do
        bin.install "back2base"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/back2base/back2base-dist/releases/download/v0.35.0/back2base_linux_amd64.tar.gz"
      sha256 "fcbd9b0f8eb0ce3b43801521701be1b067831530861b58e68c4f2818a589355b"
      define_method(:install) do
        bin.install "back2base"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/back2base/back2base-dist/releases/download/v0.35.0/back2base_linux_arm64.tar.gz"
      sha256 "6fdd93122e0d6999f5c0f7267fc0eb13cc490c322223e39b09760712eb01d562"
      define_method(:install) do
        bin.install "back2base"
      end
    end
  end

  def post_install
    # Best-effort base-image pre-pull so the first `back2base run` doesn't
    # have to fetch ~500MB on a cold start. Then prune older base/compose
    # images so the user doesn't accumulate multi-GB drift across upgrades.
    # Both steps are skipped silently when docker isn't installed or
    # reachable — never fails the brew install.
    if which("docker")
      system "docker", "pull", "ramseymcgrath/back2base-base:latest"
      system "#{bin}/back2base", "prune", "--yes", "--quiet"
    end
  end

  def caveats
    <<~EOS
      back2base launches a containerized Claude Code session.

      First run pulls the base image (~500MB) and builds a thin local
      layer on top. To pre-fetch / pre-build ahead of time:

        docker pull ramseymcgrath/back2base-base:latest
        back2base build

      Sign in to enable cloud sync + memory MCP:

        back2base login
    EOS
  end

  test do
    system "#{bin}/back2base", "version"
  end
end
