# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Back2base < Formula
  desc "Containerized Claude Code with curated MCP servers"
  homepage "https://back2base.net"
  version "0.38.1"
  license "MIT"

  depends_on "docker" => :optional

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/back2base/back2base-dist/releases/download/v0.38.1/back2base_darwin_amd64.tar.gz"
      sha256 "412700e569fbd8cf6e1420f6c6c6d670c77b9e34b1a0273bad23e71cc70b9151"

      define_method(:install) do
        bin.install "back2base"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/back2base/back2base-dist/releases/download/v0.38.1/back2base_darwin_arm64.tar.gz"
      sha256 "1e0383760071c8ecc6071fedec8e2ca7716dc55d6097b24a98022354346a5579"

      define_method(:install) do
        bin.install "back2base"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/back2base/back2base-dist/releases/download/v0.38.1/back2base_linux_amd64.tar.gz"
      sha256 "70a9e83950717e5dec33a13405ec025bb8ae43142de8aa213230df8906020923"
      define_method(:install) do
        bin.install "back2base"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/back2base/back2base-dist/releases/download/v0.38.1/back2base_linux_arm64.tar.gz"
      sha256 "67bd839cd9db769d9536206efed3de45981c02052a50f3c4ec39ef32c2612a4d"
      define_method(:install) do
        bin.install "back2base"
      end
    end
  end

  def post_install
    # Best-effort base-image pre-pull so the first `back2base run` doesn't
    # have to fetch ~500MB on a cold start. Then prune older base/compose
    # images so the user doesn't accumulate multi-GB drift across upgrades.
    # Both steps are skipped silently when docker isn't installed or
    # reachable — never fails the brew install.
    if which("docker")
      system "docker", "pull", "ramseymcgrath/back2base-base:latest"
      system "#{bin}/back2base", "prune", "--yes", "--quiet"
    end
  end

  def caveats
    <<~EOS
      back2base launches a containerized Claude Code session.

      First run pulls the base image (~500MB) and builds a thin local
      layer on top. To pre-fetch / pre-build ahead of time:

        docker pull ramseymcgrath/back2base-base:latest
        back2base build

      Sign in to enable cloud sync + memory MCP:

        back2base login
    EOS
  end

  test do
    system "#{bin}/back2base", "version"
  end
end
