# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Back2base < Formula
  desc "Containerized Claude Code with curated MCP servers"
  homepage "https://back2base.net"
  version "0.19.1"
  license "MIT"

  depends_on "docker" => :optional

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/ramseymcgrath/back2base-dist/releases/download/v0.19.1/back2base_darwin_amd64.tar.gz"
      sha256 "36196b73031885f81eee56482051588a1e6aee2a1c20c75d51e3b804055065be"

      define_method(:install) do
        bin.install "back2base"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/ramseymcgrath/back2base-dist/releases/download/v0.19.1/back2base_darwin_arm64.tar.gz"
      sha256 "6cd081c9c91dafaaa29e8c16eac3645ffedf58e56c1b742ad03b1e04e964eaa5"

      define_method(:install) do
        bin.install "back2base"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/ramseymcgrath/back2base-dist/releases/download/v0.19.1/back2base_linux_amd64.tar.gz"
      sha256 "a5a8cb06c546b282462e85e9d231fc1dfb6b832091700d8115b99f07392d4f40"
      define_method(:install) do
        bin.install "back2base"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/ramseymcgrath/back2base-dist/releases/download/v0.19.1/back2base_linux_arm64.tar.gz"
      sha256 "78c6288ca42159c33eaaeefa95318c88264b8c8c34bf6e47b8f2dfd706fb67cb"
      define_method(:install) do
        bin.install "back2base"
      end
    end
  end

  test do
    system "#{bin}/back2base", "version"
  end
end
