# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class OssBack2base < Formula
  desc "Containerized Claude Code with a configurable MCP server registry (OSS)"
  homepage "https://github.com/back2base/oss-back2base"
  version "0.2.0"
  license "MIT"

  depends_on "docker" => :optional

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/Back2Base/oss-back2base/releases/download/v0.2.0/oss-back2base_darwin_amd64.tar.gz"
      sha256 "579d2afd36d4ee95a2a16367efb86310c56ad9b398f288aec11b169836e5cb05"

      define_method(:install) do
        bin.install "oss-back2base"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/Back2Base/oss-back2base/releases/download/v0.2.0/oss-back2base_darwin_arm64.tar.gz"
      sha256 "f7e0b8bb2688753b0260c2fddebb2bd9ad058102386b3acc2eb5c0a7d73cdf10"

      define_method(:install) do
        bin.install "oss-back2base"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/Back2Base/oss-back2base/releases/download/v0.2.0/oss-back2base_linux_amd64.tar.gz"
      sha256 "887da544b37e4cae65e401061097bcfa873181c296b3009120dee0653f149ab8"
      define_method(:install) do
        bin.install "oss-back2base"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/Back2Base/oss-back2base/releases/download/v0.2.0/oss-back2base_linux_arm64.tar.gz"
      sha256 "31e65f72128a2da9a58a15f919a41afedc4a1d94cfc01a322a28dfae446c53f2"
      define_method(:install) do
        bin.install "oss-back2base"
      end
    end
  end

  def caveats
    <<~EOS
      oss-back2base launches a containerized Claude Code session.

      First run extracts the embedded container payload to
      ~/.local/share/back2base and builds the image (~500 MB pull
      plus a thin local layer). To pre-fetch the base image:

        docker pull ramseymcgrath/back2base-base:latest
        oss-back2base build

      Drop your Anthropic credentials into ~/.config/back2base/env
      before the first launch. See env.example in the repo for the
      full catalog.
    EOS
  end

  test do
    system "#{bin}/oss-back2base", "version"
  end
end
