# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class OssBack2base < Formula
  desc "Containerized Claude Code with a configurable MCP server registry (OSS)"
  homepage "https://github.com/back2base/oss-back2base"
  version "0.3.0"
  license "MIT"

  depends_on "docker" => :optional

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/Back2Base/oss-back2base/releases/download/v0.3.0/oss-back2base_darwin_amd64.tar.gz"
      sha256 "6de01a0bcaa7872f174006ba19e680405adabaaabd4a8c82ecc023a4facd69f3"

      define_method(:install) do
        bin.install "oss-back2base"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/Back2Base/oss-back2base/releases/download/v0.3.0/oss-back2base_darwin_arm64.tar.gz"
      sha256 "3e18fef684062f25cc6f44a36e36364d19db4bf7da1dcba832d1e264686f5dcd"

      define_method(:install) do
        bin.install "oss-back2base"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/Back2Base/oss-back2base/releases/download/v0.3.0/oss-back2base_linux_amd64.tar.gz"
      sha256 "56fb21e124cbec41fc596b85f79ac1a5e4c1f275c73a3aba46ea70fad327650f"
      define_method(:install) do
        bin.install "oss-back2base"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/Back2Base/oss-back2base/releases/download/v0.3.0/oss-back2base_linux_arm64.tar.gz"
      sha256 "aebd3d3e526fc2dc99011cf6d0fe031808d02aef77e352909ad9a0ae9b26e7ad"
      define_method(:install) do
        bin.install "oss-back2base"
      end
    end
  end

  def caveats
    <<~EOS
      oss-back2base launches a containerized Claude Code session.

      First run extracts the embedded container payload to
      ~/.local/share/back2base and builds the image (~500 MB pull
      plus a thin local layer). To pre-fetch the base image:

        docker pull ramseymcgrath/back2base-base:latest
        oss-back2base build

      Drop your Anthropic credentials into ~/.config/back2base/env
      before the first launch. See env.example in the repo for the
      full catalog.
    EOS
  end

  test do
    system "#{bin}/oss-back2base", "version"
  end
end
