# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class OssBack2base < Formula
  desc "Containerized Claude Code with a configurable MCP server registry (OSS)"
  homepage "https://github.com/back2base/oss-back2base"
  version "0.1.3"
  license "MIT"

  depends_on "docker" => :optional

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/Back2Base/oss-back2base/releases/download/v0.1.3/oss-back2base_darwin_amd64.tar.gz"
      sha256 "0c35f70a4ab1a94b68468568652cf8fce3e301c4f5cdda39c3dab94c85073801"

      define_method(:install) do
        bin.install "oss-back2base"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/Back2Base/oss-back2base/releases/download/v0.1.3/oss-back2base_darwin_arm64.tar.gz"
      sha256 "2ab3957ddef493543b6ed86943404a2c978003d39b1c8fa48141c40c455fcb2e"

      define_method(:install) do
        bin.install "oss-back2base"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/Back2Base/oss-back2base/releases/download/v0.1.3/oss-back2base_linux_amd64.tar.gz"
      sha256 "7daf490ca640db2197420e7061e85bd794508eea6240863a52553df2eb0528be"
      define_method(:install) do
        bin.install "oss-back2base"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/Back2Base/oss-back2base/releases/download/v0.1.3/oss-back2base_linux_arm64.tar.gz"
      sha256 "6dcae7de6fd5b5dd4335d1cf3fbd5845486f20cf0f7f40ae4ffe1867594882a4"
      define_method(:install) do
        bin.install "oss-back2base"
      end
    end
  end

  def caveats
    <<~EOS
      oss-back2base launches a containerized Claude Code session.

      First run extracts the embedded container payload to
      ~/.local/share/back2base and builds the image (~500 MB pull
      plus a thin local layer). To pre-fetch the base image:

        docker pull ramseymcgrath/back2base-base:latest
        oss-back2base build

      Drop your Anthropic credentials into ~/.config/back2base/env
      before the first launch. See env.example in the repo for the
      full catalog.
    EOS
  end

  test do
    system "#{bin}/oss-back2base", "version"
  end
end
